server.port: 7002
server.error.include-message: always
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: jatinder
    password: root
    url: jdbc:mysql://localhost/review-db
    hikari:
      initialization-fail-timeout: 60000

logging:
  level:
    root: INFO
    app.flowkind: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE