server.port: 7002
server.error.include-message: always
#myip: "flowkind.eastus2.cloudapp.azure.com"
myip: "localhost"
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: jatinder
    password: root
#    url: jdbc:mysql://flowkind.eastus2.cloudapp.azure.com/review-db
    hikari:
      initialization-fail-timeout: 60000
##      max-lifetime: 1820000
#      maximum-pool-size: 5
#      minimum-idle: 3
    url: jdbc:mysql://localhost/review-db
  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      default.contentType: application/json
      bindings:
        messageProcessor-in-0:
          destination: reviews
          group: reviewsGroup
          prefix: flowkind
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              receive-timeout: 200
      kafka:
        binder:
          brokers: ${myip}
          defaultBrokerPort: 9092
        bindings:
          messageProcessor-in-0:
            consumer:
              enableDlq: true
  rabbitmq:
    host: ${myip}
    port: 5672
    username: guest
    password: guest
  application:
    name: review

logging:
  level:
    root: INFO
    app.flowkind: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  api-docs:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5