version: "3.9"
# using github container registry
services:
  product:
    build: microservices/flowkind-core-product-service
    image: ghcr.io/jatinderkumarchaurasia/flowkind/product-service
    #    image: registry.gitlab.com/jatinderkumarchaurasia/flowkind/product-service
    container_name: product-service
    mem_reservation: 256m
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka"
    depends_on:
      - mongodb
      - kafka

  product-p1:
    build: microservices/flowkind-core-product-service
    image: ghcr.io/jatinderkumarchaurasia/flowkind/product-service
    #    image: registry.gitlab.com/jatinderkumarchaurasia/flowkind/product-service
    container_name: product-service-p1
    mem_reservation: 256m
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka"
    depends_on:
      - mongodb
      - kafka

  recommendation:
    build: microservices/flowkind-core-recommendation-service
    image: ghcr.io/jatinderkumarchaurasia/flowkind/recommendation-service
    #    image: registry.gitlab.com/jatinderkumarchaurasia/flowkind/recommendation-service
    container_name: recommendation-service
    mem_reservation: 256m
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka"
    depends_on:
      - mongodb
      - kafka

  recommendation-p1:
    build: microservices/flowkind-core-recommendation-service
    image: ghcr.io/jatinderkumarchaurasia/flowkind/recommendation-service
    #    image: registry.gitlab.com/jatinderkumarchaurasia/flowkind/recommendation-service
    container_name: recommendation-service-p1
    mem_reservation: 256m
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka"
    depends_on:
      - mongodb
      - kafka

  review:
    build: microservices/flowkind-core-review-service
    image: ghcr.io/jatinderkumarchaurasia/flowkind/review-service
    #    image: registry.gitlab.com/jatinderkumarchaurasia/flowkind/review-service
    container_name: review-service
    mem_reservation: 256m
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka"
    depends_on:
      - mysql
      - kafka
    command: ["./wait-for-it.sh"]

  review-p1:
    build: microservices/flowkind-core-review-service
    image: ghcr.io/jatinderkumarchaurasia/flowkind/review-service
    #    image: registry.gitlab.com/jatinderkumarchaurasia/flowkind/review-service
    container_name: review-service-p1
    mem_reservation: 256m
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka"
    depends_on:
      - mysql
      - kafka
    command: [ "./wait-for-it.sh" ]

  product-composite:
    build: microservices/flowkind-product-compose-service
    image: ghcr.io/jatinderkumarchaurasia/flowkind/product-composite-service
    #    image: registry.gitlab.com/jatinderkumarchaurasia/flowkind/product-composite-service
    container_name: product-composite-service
    mem_reservation: 256m
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,kafka"
    depends_on:
      - kafka

  mysql:
    image: mysql:latest
    container_name: mysql_flowkind
    mem_reservation: 256m
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=jatinder
      - MYSQL_PASSWORD=root
    healthcheck:
      test: "/usr/bin/mysql --user=jatinder --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  mongodb:
    image: mongo:latest
    mem_reservation: 256m
    ports:
      - '27017:27017'
    command:
      - mongod
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60

  kafka:
    image: wurstmeister/kafka:latest
    mem_reservation: 128m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    mem_reservation: 128m
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper