spring:
  config:
    activate:
      on-profile: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
  rabbitmq:
    host: rabbitmq
server:
  port: 8080

flowkind-app:
  flowkind-core-product-service:
    host: product
    port: 7001
  flowkind-core-review-service:
    host: review
    port: 7002
  flowkind-core-recommendation-service:
    host: recommendation
    port: 7003
