spring:
  config:
    activate:
      on-profile: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
  rabbitmq:
    host: rabbitmq
server:
  port: 8080

#flowkind-app:
#  flowkind-core-product-service:
#    host: product
#    port: 8080
#  flowkind-core-review-service:
#    host: review
#    port: 7002
#  flowkind-core-recommendation-service:
#    host: recommendation
#    port: 7003

eureka:
  client:
    service-url:
      defaultZone: 'http://eureka:8761/eureka'
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5