server.port: 7001
server.error.include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      repositories:
        type: auto

logging:
  level:
    root: INFO
    app.flowkind: DEBUG