server.port: 7001
server.error.include-message: always
myip: "localhost"
#myip: "flowkind.eastus2.cloudapp.azure.com"
spring:
  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      default:
        contentType: application/json

      bindings:
        messageProcessor-in-0:
          destination: products
          group: productsGroup
          prefix: flowkind
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0

      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              receive-timeout : 200
      kafka:
        binder:
          brokers: ${myip}
          defaultBrokerPort: 9092
        bindings:
          messageProcessor-in-0:
            consumer:
              enableDlq: true

  data:
    mongodb:
      host: ${myip}
      port: 27017
      database: product-db
      repositories:
        type: auto
      auto-index-creation: true
  rabbitmq:
    host: ${myip}
#    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    app.flowkind: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  api-docs:
    enabled: false