spring:
  config:
    activate:
      on-profile: kafka
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          replication-factor: 1
  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoint:
    health:
      enabled: true
  health:
    rabbit:
      enabled: false