spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
  rabbitmq:
    host: rabbitmq
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: 'http://eureka:8761/eureka/'
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5